### PR TITLE
+options to hide with game/OP UI

### PR DESCRIPTION
**Pull request by ezio416**

### CODE REVIEW

**Comment by codecat** [comment]
We already have (a more advanced) way to configure this in the plugin, so this is not needed.

**Comment by ezio416** [comment]
I don't quite understand. In the advanced visibility settings, you can hide each component with hidden game UI (admittedly I did miss this), but the text underneath says `requires the option "Hide overlay on hidden game UI" under "General" to be disabled` which does not exist. There's also no option for hiding with Openplanet UI.

**Comment by codecat** [comment]
Oh, I might've moved that to the Overlay tab, I don't remember. It should be there somewhere!

**Comment by ezio416** [comment]
There's no "Overlay" setting tab, and I don't see it anywhere in the code

**Comment by ezio416** [comment]
If you mean the main Openplanet "Overlay" tab, that toggle is way too global and applies to all plugins. Also would not allow me to have hidden game UI and still show OP UI, which often I do wish to do

**Comment by codecat** [comment]
If you leave the setting disabled, you can still have hidden game UI and visible Openplanet UI (and Dashboard's advanced visibility settings)

**Pull request closed without merging**
