### PR TITLE
Added option for gearbox text to change color based on gear.

### PR DESCRIPTION
**Pull request by DR3AMCR4SH**

### CODE REVIEW

**Comment by codecat** [comment]
Thanks for the PR! But environments can have more than just 5 gears, Canyon/Valley/Lagoon for example can all go up to 7, and on Turbo, Stadium even seems to have 9 gears (see #20). Also, you can go into gear 0 when driving backwards, so perhaps that should also be covered.

**Comment by DR3AMCR4SH** [comment]
I see, I wasn't thinking about games other than TM 2020. If the code is similar for the other games as well it shouldn't be too difficult. I won't be able to test it super soon since I don't own the games yet. I'll definitely add gear 0, though, I forgot about that one. XD

**Comment by codecat** [comment]
I think it probably makes sense to use [preprocessor defines](https://openplanet.dev/docs/reference/preprocessor) to add gears up to 7 (for Maniaplanet) or 9 (for Turbo).

**Comment by DR3AMCR4SH** [comment]
done!

**Comment by codecat** [comment]
Thank you!

**Pull request merged**
